// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdeGulkbGfGEIQw9abdfIUcvN01ZURNLw',
    appId: '1:596189352325:android:e7e00209c4f988048974ec',
    messagingSenderId: '596189352325',
    projectId: 'announcement-app-c6974',
    storageBucket: 'announcement-app-c6974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC3P2wOVS78mtusq4AV85omDwYu0ibCh0',
    appId: '1:596189352325:ios:3bce6f835e2dec608974ec',
    messagingSenderId: '596189352325',
    projectId: 'announcement-app-c6974',
    storageBucket: 'announcement-app-c6974.appspot.com',
    iosBundleId: 'com.example.schoolAnnouncements',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5yQ3e5bPOSiJTy-IblL0LSuZGC126-SQ',
    appId: '1:596189352325:web:196a5e4b5b78f4218974ec',
    messagingSenderId: '596189352325',
    projectId: 'announcement-app-c6974',
    authDomain: 'announcement-app-c6974.firebaseapp.com',
    storageBucket: 'announcement-app-c6974.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC3P2wOVS78mtusq4AV85omDwYu0ibCh0',
    appId: '1:596189352325:ios:3bce6f835e2dec608974ec',
    messagingSenderId: '596189352325',
    projectId: 'announcement-app-c6974',
    storageBucket: 'announcement-app-c6974.appspot.com',
    iosBundleId: 'com.example.schoolAnnouncements',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5yQ3e5bPOSiJTy-IblL0LSuZGC126-SQ',
    appId: '1:596189352325:web:0e3965680907e6a28974ec',
    messagingSenderId: '596189352325',
    projectId: 'announcement-app-c6974',
    authDomain: 'announcement-app-c6974.firebaseapp.com',
    storageBucket: 'announcement-app-c6974.appspot.com',
  );

}